FlatFilers/Adapter

- src/index.ts
Bug fix
'close' event is not firing
'close' even should be firing now.
> moved emit of close event

- .editorconfig
- .gitignore
- src/index.ts
- src/obj.load-options.ts
- src/obj.meta.ts
- src/results.ts
- src/streamed-results.ts
- tslint.json
> Adds ability to stream data in chunks rather than accept it all at once

- package.json
changing version number
no behavior changes
no behavior changes
> updating version for new npm package

- package.json
New version number for npm
no behavior change
No behavior change
> update current version to 0.2.13

- README.md
Doc updates
Documentation has wrong variable being used. 
Documentation in readme now has the correct variable being used. 
> Fixing small documentation error

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
> chore: add codeql

- package.json
- src/index.ts
- src/obj.before-fetch.ts
Featuer
__-__
Added ability to modify headers on each request.
Needs documentation update
> feat(adapter): added beforeFetchCallback;

- package.json
- src/index.ts
update
`displaySuccess`, `requestCorrectionsFromUser ` and `displayError` messages are required
`displaySuccess`, `requestCorrectionsFromUser ` and `displayError` messages are optional
> refactor(adapter): messages are now optional

- package.json
- src/index.ts
- src/obj.interaction-event.ts
feature
-
Ability to receive interaction events from Portal (mousedown, keydown and mousemove)
https://linear.app/flatfile/issue/FLA-809/callback-to-receive-interaction-events-from-portal
> feat(adapter): added callback to receive interaction events

- package-lock.json
- package.json
chore
no check before commit
Added husky that will run lint and prettier before commit
-
>  chore(adapter): added husky;

- package-lock.json
- package.json
- src/index.ts
feature
-
Ability to change Portal language using `importer.setLanguage('de')`
-
> feat(adapter): ability to set language using method

- README.md
> docs(adapter): updated readme

- package.json
- src/obj.meta.ts
- src/obj.settings.ts
- src/results.ts
type update
\-
added `allowFormatting` (boolean)
\-
> feat(adapter): added allowFormatting (boolean)

- README.md
- package-lock.json
- package.json
- src/obj.settings.ts
Fixes and Issue with the types
Adds a note to the README
No type definition for the new googleFonts addition to integrations
> updates types and adds a note to the README

- package-lock.json
- package.json
- src/obj.theme.ts
chore
Added missing theme prop types;
> chore(adapter): added missing ts theme prop types;

- package.json
- src/obj.settings.ts
- src/obj.theme.ts
Updated types for header-selection update;
> chore(adapter): added types for header-selection update;

- package-lock.json
- package.json
- src/index.ts
- src/obj.hooks.ts
feature
Added `registerStepHook`
\-
\-
> feat(adapter): added registerStepHook

- src/index.ts
- src/obj.settings.ts
> added virtual columns;

- README.md
- package.json
Small PR to release final (non-beta) version to npm
> feat: release 2.8.0 to npm

- package-lock.json
- package.json
- src/interfaces/obj.settings.ts
> feat(adapter): added full screen;

- src/importer.ts
Depends on https://github.com/FlatFilers/Mono/pull/1986
> feat(adapter): added registerVirtualRecordHook();

- package-lock.json
- package.json
- src/importer.ts
- src/interfaces/obj.record.ts
- src/interfaces/obj.settings.ts
- src/results.ts
> fix(adapter): added types; undeprecated displayError();
